
global:
  scrape_interval:     5s # Set the scrape interval to every 5 seconds.
  evaluation_interval: 5s # Evaluate rules every 5 seconds.

scrape_configs:
  - job_name: 'product-master-engine-ms-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'client-ms-app:8083' ]