server:
  port: 8081
  compression:
    enabled: true
    min-response-size: 1024
spring:
  mvc:
    async:
      request-timeout: "1200s"
  application:
    name: "order-handler-ms"
  devtools:
    add-properties: false
  profiles:
    include: null
  main:
    lazy-initialization: false
management:
  tracing:
    sampling:
      probability: 0.0
    baggage:
      correlation:
        fields:
          - "message-id"
      remote-fields: "message-id"
  endpoints:
    web:
      exposure:
        include: "*"
      path-mapping:
        loggers: "api/v1/orders-handler/actuator/loggers"
  endpoint:
    health:
      probes:
        enabled: true
      show-details: "always"
    loggers:
      access: unrestricted
    shutdown:
      access: unrestricted
    refresh:
      access: unrestricted
  health:
    diskspace:
      enabled: false
    ping:
      enabled: false
    refresh:
      enabled: true
  info:
    env:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
logging:
  level:
    org:
      springframework:
        boot:
          actuate: "DEBUG"
info:
  app:
    name: "Order Handler Microservice"
    description: "Manage Orders for the Project"
    version: "1.0.0"

endpoints:
  shutdown:
    enabled: true

infrastructure:
  adapters:
    db:
      status: "ENABLED"

cors.allowed:
  -
    path: "/**"
    headers:
      - "*"
    origins:
      - "http://localhost:4200"
      - "http://localhost:8080" # For Prometheus
      - "https://sgb-web-prod.azureedge.net"
    methods:
      - "HEAD"
      - "OPTIONS"
      - "GET"
      - "POST"
      - "PUT"
      - "PATCH"
      - "DELETE"
  -
    path: "/somePath/**"
    headers:
      - "*"
    origins:
      - "http://localhost:4200"
    methods:
      - "GET"
      - "POST"
